name: SignShopHotel
main: org.wargamer2010.sshotel.SSHotel
version: 1.0.7Dev
dev-url: http://dev.bukkit.org/server-mods/signshop
depend: [SignShop]
author: Wargamer2010
commands:
  signshophotel:
    description: Admin commands for SignShopHotel
    usage: /signshophotel [reload]
